
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('vanbuild').del()
    .then(function () {
      // Inserts seed entries
      return knex('vanbuild').insert([
        {
          id: 1,
          name: 'Gomez',
          make: 'Ram',
          model: 'Promaster',
          year: 2019,
          color: 'white',
          flooring_material: 'pine',
          flooring_installed: false,
          insulation_material: 'spray foam',
          insulation_installed: false,
          wall_material: 'pine',
          wall_installed: false,
          battery_house: true,
          battery_brand: 'Renogy',
          battery_size: 400,
          battery_installed: false,
          inverter: true,
          inverter_brand: 'Renogy',
          inverter_size: 3000,
          inverter_installed: false,
          solar_power: true,
          solar_panel_brand: 'Renogy',
          solar_panel_watts: 480,
          solar_installed: false,
          solar_controller_brand: 'Renogy',
          solar_controller_type: 'MPPT',
          solar_controller_installed: false,
          alternator_power: true,
          alternator_power_brand: 'Blue Sea Systems',
          alternator_power_type: 'Automatic Charge Relay',
          alternator_power_installed: false,
          shore_power: true,
          shore_power_installed: false,
          plumbing: true,
          water_pump_type: 'electric',
          water_pump_brand: 'Shurflo',
          water_pump_description: '12V',
          water_pump_installed: false,
          water_heater: true,
          water_heater_brand: 'Bosch',
          water_heater_type: '2 gallon',
          water_heater_installed: false,
          fresh_water_tank: true,
          fresh_water_tank_capacity: 23,
          fresh_water_tank_installed: false,
          grey_water_tank: true,
          grey_water_tank_capacity: 9,
          grey_water_tank_installed: false,
          black_water_tank: false,
          black_water_tank_capacity: null,
          black_water_tank_installed: false,
          toilet: true,
          toilet_type: 'cassette',
          toilet_brand: 'Dometic',
          toilet_installed: false,
          heater: true,
          heater_type: 'gasoline',
          heater_brand: 'Webasto',
          heater_model: '12V Air Top',
          heater_installed: false,
          ac: false,
          ac_brand: null,
          ac_model: null,
          ac_installed: false,
          fan: true,
          fan_brand: 'MaxxAir',
          fan_model: 'Deluxe',
          fan_installed: false,
          fridge: true,
          fridge_brand: 'Dometic',
          fridge_model: 'something',
          fridge_installed: false,
          lights: true,
          lights_number: 12,
          lights_installed: false,
          notes: 'Notes go here',
          img_url: 'http://'
        },
        {
          id: 2,
          name: 'Chester',
          make: 'Mercedes',
          model: 'Sprinter',
          year: 2014,
          color: 'Grey',
          flooring_material: 'vinyl',
          flooring_installed: true,
          insulation_material: 'foam board',
          insulation_installed: true,
          wall_material: 'baltic birch',
          wall_installed: false,
          battery_house: true,
          battery_brand: 'Battle Born',
          battery_size: 200,
          battery_installed: true,
          inverter: true,
          inverter_brand: 'Renogy',
          inverter_size: 3000,
          inverter_installed: true,
          solar_power: true,
          solar_panel_brand: 'Renogy',
          solar_panel_watts: 400,
          solar_installed: true,
          solar_controller_brand: 'Renogy',
          solar_controller_type: 'MPPT',
          solar_controller_installed: true,
          alternator_power: true,
          alternator_power_brand: 'Blue Sea Systems',
          alternator_power_type: 'Automatic Charge Relay',
          alternator_power_installed: true,
          shore_power: true,
          shore_power_installed: true,
          plumbing: true,
          water_pump_type: 'electric',
          water_pump_brand: 'Shurflo',
          water_pump_description: '12V',
          water_pump_installed: true,
          water_heater: true,
          water_heater_brand: 'Bosch',
          water_heater_type: '4 gallon, on demand',
          water_heater_installed: true,
          fresh_water_tank: true,
          fresh_water_tank_capacity: 33,
          fresh_water_tank_installed: true,
          grey_water_tank: true,
          grey_water_tank_capacity: 10,
          grey_water_tank_installed: true,
          black_water_tank: true,
          black_water_tank_capacity: 20,
          black_water_tank_installed: true,
          toilet: true,
          toilet_type: 'compost',
          toilet_brand: 'Natures Head',
          toilet_installed: true,
          heater: true,
          heater_type: 'diesel',
          heater_brand: 'Webasto',
          heater_model: '12V Air Top',
          heater_installed: true,
          ac: false,
          ac_brand: null,
          ac_model: null,
          ac_installed: false,
          fan: true,
          fan_brand: 'Fantastic Fan',
          fan_model: 'Plus',
          fan_installed: true,
          fridge: true,
          fridge_brand: 'Dometic',
          fridge_model: 'something else',
          fridge_installed: true,
          lights: true,
          lights_number: 8,
          lights_installed: true,
          notes: 'Notes go here',
          img_url: 'http://'
        },
        {
          id: 3,
          name: 'Rambler',
          make: 'Ford',
          model: 'Transit',
          year: 2017,
          color: 'white',
          flooring_material: 'wood composite',
          flooring_installed: true,
          insulation_material: 'denim',
          insulation_installed: true,
          wall_material: 'pine',
          wall_installed: true,
          battery_house: false,
          battery_brand: null,
          battery_size: null,
          battery_installed: false,
          inverter: false,
          inverter_brand: null,
          inverter_size: null,
          inverter_installed: false,
          solar_power: false,
          solar_panel_brand: null,
          solar_panel_watts: null,
          solar_installed: false,
          solar_controller_brand: null,
          solar_controller_type: null,
          solar_controller_installed: false,
          alternator_power: false,
          alternator_power_brand: null,
          alternator_power_type: null,
          alternator_power_installed: false,
          shore_power: false,
          shore_power_installed: false,
          plumbing: true,
          water_pump_type: 'manual',
          water_pump_brand: 'Amazon special',
          water_pump_description: 'foot pump',
          water_pump_installed: true,
          water_heater: false,
          water_heater_brand: null,
          water_heater_type: null,
          water_heater_installed: false,
          fresh_water_tank: true,
          fresh_water_tank_capacity: 23,
          fresh_water_tank_installed: false,
          grey_water_tank: true,
          grey_water_tank_capacity: 9,
          grey_water_tank_installed: false,
          black_water_tank: false,
          black_water_tank_capacity: null,
          black_water_tank_installed: false,
          toilet: true,
          toilet_type: 'cassette',
          toilet_brand: 'Dometic',
          toilet_installed: true,
          heater: false,
          heater_type: null,
          heater_brand: null,
          heater_model: null,
          heater_installed: false,
          ac: false,
          ac_brand: null,
          ac_model: null,
          ac_installed: false,
          fan: true,
          fan_brand: 'MaxxAir',
          fan_model: 'Deluxe',
          fan_installed: true,
          fridge: false,
          fridge_brand: null,
          fridge_model: null,
          fridge_installed: false,
          lights: false,
          lights_number: null,
          lights_installed: false,
          notes: 'Notes go here',
          img_url: 'http://'
        }
      ]);
    });
};
